checkpoint: "../train/training-output/checkpoint/db6e7078-7b2e-48cb-b3d7-57892d093c97/inference-last.ckpt"

lead_time: 240 # hours

date: 2023-01-01T12

input:
  dataset: "../data/replay.zarr"

output:
  netcdf: "2023-01-01T12.nc"
