name: eagle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ufs2arco
  - pip
  - pip:
      - torch<2.7
      - anemoi-datasets==0.5.26
      - anemoi-graphs==0.6.4
      - anemoi-models==0.9.2
      - anemoi-training==0.6.2
      - anemoi-inference==0.7.1
      - anemoi-utils==0.4.35
      - anemoi-transform==0.1.16
      - flash-attn<2.8 --no-build-isolation
      - eagle-tools
