checkpoint: "../train/training/training-output/checkpoint/35a9632c-ab04-4284-af5e-4defcef37cff/inference-last.ckpt"

lead_time: 240 # hours

date: 2023-01-01T12

input:
  dataset: "../data/replay.zarr"

output:
  netcdf: "2023-01-01T12.nc"
