baseline:
  compare: true
  name: GFS
  url: https://noaa-gfs-bdp-pds.s3.amazonaws.com/gfs.{yyyymmdd}/{hh}/atmos/gfs.t{hh}z.pgrb2.0p25.f{fh:03}
cycles:
  - 2023-01-01T12:00:00
forecast:
  coords:
    latitude: latitude
    level: level
    longitude: longitude
    time:
      inittime: forecast_reference_time
      validtime: time
  name: replay_hello_world_example
  path: /path/to/your/files/2023-01-01T12.240h_post.nc
  projection:
    proj: latlon
leadtimes:
  start: "00:00:00"
  step: "06:00:00"
  stop: "240:00:00"
meta:
  grids: "{{ meta.workdir }}/grids"
  levels: &levels [925]
  workdir: /path/to/your/files/workdir/
paths:
  grids:
    baseline: "{{ meta.grids }}/baseline"
    forecast: "{{ meta.grids }}/forecast"
  run: "{{ meta.workdir }}/run"
variables:
  tmp2m:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  spfh:
    level_type: isobaricInhPa
    levels: *levels
    name: q
  tmp:
    level_type: isobaricInhPa
    levels: *levels
    name: t
  ugrd:
    level_type: isobaricInhPa
    levels: *levels
    name: u
  vgrd:
    level_type: isobaricInhPa
    levels: *levels
    name: v
