# if you are just running 1 initialization, make start==end
initializations_to_run:
  start: "2023-01-01T12:00:00"
  end: "2023-01-01T12:00:00"
  freq: "6h"

# path to raw inference files you want to post process
raw_inference_files_base_path: "../inference"

# this next portion lists all variable info out so the script knows what variables to process.
# can be helpful if you don't care about all variables or levels.
# it will only process and save out what you list below.
level_variables:
  - spfh
  - tmp
  - ugrd
  - vgrd

levels:
  - 25
  - 75
  - 125
  - 175
  - 225
  - 275
  - 325
  - 375
  - 425
  - 475
  - 525
  - 575
  - 625
  - 675
  - 725
  - 775
  - 825
  - 875
  - 925
  - 975

vars_of_interest:
  - pressfc
  - spfh_25
  - spfh_75
  - spfh_125
  - spfh_175
  - spfh_225
  - spfh_275
  - spfh_325
  - spfh_375
  - spfh_425
  - spfh_475
  - spfh_525
  - spfh_575
  - spfh_625
  - spfh_675
  - spfh_725
  - spfh_775
  - spfh_825
  - spfh_875
  - spfh_925
  - spfh_975
  - spfh2m
  - tmp_25
  - tmp_75
  - tmp_125
  - tmp_175
  - tmp_225
  - tmp_275
  - tmp_325
  - tmp_375
  - tmp_425
  - tmp_475
  - tmp_525
  - tmp_575
  - tmp_625
  - tmp_675
  - tmp_725
  - tmp_775
  - tmp_825
  - tmp_875
  - tmp_925
  - tmp_975
  - tmp2m
  - ugrd_25
  - ugrd_75
  - ugrd_125
  - ugrd_175
  - ugrd_225
  - ugrd_275
  - ugrd_325
  - ugrd_375
  - ugrd_425
  - ugrd_475
  - ugrd_525
  - ugrd_575
  - ugrd_625
  - ugrd_675
  - ugrd_725
  - ugrd_775
  - ugrd_825
  - ugrd_875
  - ugrd_925
  - ugrd_975
  - ugrd10m
  - vgrd_25
  - vgrd_75
  - vgrd_125
  - vgrd_175
  - vgrd_225
  - vgrd_275
  - vgrd_325
  - vgrd_375
  - vgrd_425
  - vgrd_475
  - vgrd_525
  - vgrd_575
  - vgrd_625
  - vgrd_675
  - vgrd_725
  - vgrd_775
  - vgrd_825
  - vgrd_875
  - vgrd_925
  - vgrd_975
  - vgrd10m
